default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  host: <%= ENV['DB_DATABASE_HOST'] %>
  username: <%= ENV['DB_DATABASE_USER'] %>
  password: <%= ENV['DB_DATABASE_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: 'share_post_test'

production:
  <<: *default